name: LaTeX Document

on:
  push:
    paths-ignore:
        - "**.md"
        - "**.yml"
  pull_request:
    paths-ignore:
        - "**.md"
        - "**.yml"

jobs:
  build:
    name: Build document
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          args:  -xelatex -interaction=nonstopmode -file-line-error
          working_directory: 讲义
          root_file: 线性代数荣誉课辅学讲义.tex

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 线性代数荣誉课辅学讲义-${{ github.ref_name }}-${{ github.run_number }}.pdf
          path: |
            ${{ github.workspace }}/讲义/线性代数荣誉课辅学讲义.pdf
