name: LaTeX Document

on:
  workflow_dispatch:
  push:
    paths-ignore:
        - "**.md"
        - "latexindent.yaml"
  pull_request:
    paths-ignore:
        - "**.md"
        - "latexindent.yaml"

jobs:
  build:
    name: Build document
    runs-on: ubuntu-latest
    container: mfisherman/texlive-full:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        id: build
        working-directory: ${{ github.workspace }}
        run: |
          git config --system --add safe.directory $(pwd -P)
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          make gh-actions

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: LALU-build-${{ github.run_number }}-${{ steps.build.outputs.sha }}
          if-no-files-found: error
          path: ${{ github.workspace }}/gh-actions-build/*.pdf
